project_id = "edbuedrjojnvfquakkfv"

[functions.create-bounty-with-payment]
verify_jwt = true

[functions.contribute-to-bounty]
verify_jwt = true

[functions.generate-bounty-template]
verify_jwt = true